// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BookStats.Autorest
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for BookStatsClient.
    /// </summary>
    public static partial class BookStatsClientExtensions
    {
            /// <summary>
            /// Get stats for a book
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='bookid'>
            /// </param>
            public static BookStatsModel GetBookStats(this IBookStatsClient operations, int bookid)
            {
                return operations.GetBookStatsAsync(bookid).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get stats for a book
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='bookid'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<BookStatsModel> GetBookStatsAsync(this IBookStatsClient operations, int bookid, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetBookStatsWithHttpMessagesAsync(bookid, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
