/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * An interface representing Book.
 */
export interface Book {
  id: number;
  title: string;
  author: string;
}

/**
 * An interface representing BookWithStats.
 */
export interface BookWithStats {
  id: number;
  title: string;
  author: string;
  copiesSold?: number;
}

/**
 * An interface representing BookApiClientOptions.
 */
export interface BookApiClientOptions extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Optional Parameters.
 */
export interface BooksStoreBookOptionalParams extends msRest.RequestOptionsBase {
  body?: Book;
}

/**
 * Contains response data for the getAll operation.
 */
export type BooksGetAllResponse = Array<Book> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Book[];
    };
};

/**
 * Contains response data for the storeBook operation.
 */
export type BooksStoreBookResponse = Book & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Book;
    };
};

/**
 * Contains response data for the get operation.
 */
export type BooksGetResponse = BookWithStats & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: BookWithStats;
    };
};
