/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const Book: msRest.CompositeMapper = {
  serializedName: "Book",
  type: {
    name: "Composite",
    className: "Book",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      title: {
        required: true,
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      author: {
        required: true,
        serializedName: "author",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const BookWithStats: msRest.CompositeMapper = {
  serializedName: "BookWithStats",
  type: {
    name: "Composite",
    className: "BookWithStats",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      title: {
        required: true,
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      author: {
        required: true,
        serializedName: "author",
        type: {
          name: "String"
        }
      },
      copiesSold: {
        nullable: true,
        serializedName: "copiesSold",
        type: {
          name: "Number"
        }
      }
    }
  }
};
