/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Mappers from "../models/serviceMappers";
import { BookApiClientContext } from "../bookApiClientContext";

/** Class representing a Service. */
export class Service {
  private readonly client: BookApiClientContext;

  /**
   * Create a Service.
   * @param {BookApiClientContext} client Reference to the service client.
   */
  constructor(client: BookApiClientContext) {
    this.client = client;
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  ping(options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param callback The callback
   */
  ping(callback: msRest.ServiceCallback<void>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  ping(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  ping(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        options
      },
      pingOperationSpec,
      callback);
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const pingOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/Service/ping",
  responses: {
    200: {},
    default: {}
  },
  serializer
};
