/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * An interface representing BookStatsModel.
 */
export interface BookStatsModel {
  bookId?: number;
  copiesSold?: number;
}

/**
 * An interface representing BookStatsOptions.
 */
export interface BookStatsOptions extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Contains response data for the getBookStats operation.
 */
export type GetBookStatsResponse = BookStatsModel & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: BookStatsModel;
    };
};
